### ISSUE TITLE
maxLogSize is not working

### ISSUE THREAD

**Issue by myalban** [TypedProject/ts-log-debug#10]
I've setup ts-log-debug like this : 

const logger = new Logger('Debug');
logger.appenders
    .set('std-log', {
        type: 'stdout', layout: { type: 'production' }
    })
    .set('std-log-file', {
        type: 'file', 
        layout:{
            type: "json",
            separator: ","
        },
        filename: `${__dirname}/app.log`, 
        maxLogSize: 5000,
        backups: 3,
        compress: true
    });

But my file is 139KB and log rotator doesn't rotate it .

Does I miss something ?

Thanks,
best regards

**Comment by myalban** [comment]
Fixed from https://github.com/TypedProject/ts-log-debug/pull/11 , please merge

**Comment by Romakita** [comment]
Released :)
Thanks @myalban ;)
